// OpsReportsPage.jsx
//
// Director-facing daily operations reports viewer.
// Shows the 8am / 12pm / 5pm automated reports with coordinator
// task completion tracking, overload alerts, and activity logs.
// Reports are generated by the daily-ops-report edge function and
// stored in daily_ops_reports table.

import { useState, useEffect, useMemo } from 'react';
import TopBar from '../../components/TopBar';
import { supabase } from '../../lib/supabase';
import { useRealtimeTable } from '../../hooks/useRealtimeTable';
import { useAuth } from '../../hooks/useAuth';

const REPORT_META = {
  morning_overview: { label: 'Morning Overview', icon: '☀️', color: '#2563EB', bg: '#EFF6FF', time: '8:00 AM' },
  midday_snapshot:  { label: 'Midday Snapshot',  icon: '🕛', color: '#059669', bg: '#ECFDF5', time: '12:00 PM' },
  eod_review:       { label: 'End-of-Day Review', icon: '🌙', color: '#7C3AED', bg: '#F5F3FF', time: '5:00 PM' },
};

function fmtDate(d) {
  if (!d) return '—';
  return new Date(d + 'T00:00:00').toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' });
}
function fmtTime(ts) {
  if (!ts) return '';
  return new Date(ts).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
}

export default function OpsReportsPage() {
  const { profile } = useAuth();
  const [reports, setReports] = useState([]);
  const [overloads, setOverloads] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState(null);
  const [dateFilter, setDateFilter] = useState(new Date().toISOString().slice(0, 10));

  function load() {
    setLoading(true);
    Promise.all([
      supabase.from('daily_ops_reports')
        .select('*')
        .eq('report_date', dateFilter)
        .order('created_at', { ascending: false }),
      supabase.from('coordinator_overload_alerts')
        .select('*')
        .order('sent_at', { ascending: false })
        .limit(20),
    ]).then(([r, o]) => {
      setReports(r.data || []);
      setOverloads(o.data || []);
      setLoading(false);
    });
  }

  useEffect(() => { load(); }, [dateFilter]);
  useRealtimeTable(['daily_ops_reports', 'coordinator_overload_alerts'], load);

  const dates = useMemo(() => {
    const d = [];
    const today = new Date();
    for (let i = 0; i < 14; i++) {
      const dt = new Date(today);
      dt.setDate(today.getDate() - i);
      d.push(dt.toISOString().slice(0, 10));
    }
    return d;
  }, []);

  const canView = ['super_admin', 'admin', 'assoc_director', 'ceo'].includes(profile?.role);

  if (!canView) return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      <TopBar title="Operations Reports" subtitle="Access restricted to Directors" />
      <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--gray)' }}>
        This page is restricted to Director-level access.
      </div>
    </div>
  );

  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100%' }}>
      <TopBar
        title="Operations Reports"
        subtitle="Automated daily snapshots — coordinator task tracking & team performance"
      />
      <div style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 16 }}>

        {/* Overload alerts banner */}
        {overloads.length > 0 && (
          <div style={{ background: '#FEF2F2', border: '2px solid #DC2626', borderRadius: 10, padding: '12px 16px' }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: '#991B1B', marginBottom: 6 }}>⚠️ Recent Overload Alerts</div>
            {overloads.slice(0, 5).map(o => (
              <div key={o.id} style={{ fontSize: 12, color: '#991B1B', padding: '3px 0' }}>
                <strong>{o.coordinator_name}</strong> — {o.incomplete_count} incomplete tasks
                <span style={{ color: '#9CA3AF', marginLeft: 8 }}>{fmtTime(o.sent_at)}</span>
              </div>
            ))}
          </div>
        )}

        {/* Date selector */}
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
          <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--gray)' }}>Report Date:</span>
          <select value={dateFilter} onChange={e => setDateFilter(e.target.value)}
            style={{ padding: '5px 10px', border: '1px solid var(--border)', borderRadius: 6, fontSize: 12, background: 'var(--card-bg)' }}>
            {dates.map(d => <option key={d} value={d}>{fmtDate(d)}</option>)}
          </select>
          <div style={{ marginLeft: 'auto', fontSize: 11, color: 'var(--gray)' }}>{reports.length} report{reports.length === 1 ? '' : 's'} for this date</div>
        </div>

        {/* Report cards */}
        {loading ? (
          <div style={{ textAlign: 'center', padding: 40, color: 'var(--gray)' }}>Loading...</div>
        ) : reports.length === 0 ? (
          <div style={{ textAlign: 'center', padding: 40, color: 'var(--gray)', fontSize: 14 }}>
            No reports generated for this date yet. Reports are sent at 8am, 12pm, and 5pm ET on weekdays.
          </div>
        ) : (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 12 }}>
            {reports.map(r => {
              const meta = REPORT_META[r.report_type] || REPORT_META.morning_overview;
              const isSelected = selectedReport?.id === r.id;
              return (
                <div key={r.id}
                  onClick={() => setSelectedReport(isSelected ? null : r)}
                  style={{
                    background: isSelected ? meta.bg : 'var(--card-bg)',
                    border: `2px solid ${isSelected ? meta.color : 'var(--border)'}`,
                    borderRadius: 10, padding: '16px 18px', cursor: 'pointer',
                    transition: 'all 0.15s',
                  }}>
                  <div style={{ fontSize: 22 }}>{meta.icon}</div>
                  <div style={{ fontSize: 13, fontWeight: 700, color: meta.color, marginTop: 6 }}>{meta.label}</div>
                  <div style={{ fontSize: 11, color: 'var(--gray)', marginTop: 2 }}>
                    Generated {fmtTime(r.created_at)}
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* Expanded report */}
        {selectedReport && (
          <div style={{ background: 'var(--card-bg)', border: '1px solid var(--border)', borderRadius: 12, overflow: 'hidden' }}>
            <div style={{ padding: '14px 20px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div>
                <span style={{ fontSize: 14, fontWeight: 700 }}>
                  {REPORT_META[selectedReport.report_type]?.icon} {REPORT_META[selectedReport.report_type]?.label}
                </span>
                <span style={{ fontSize: 11, color: 'var(--gray)', marginLeft: 12 }}>
                  {fmtDate(selectedReport.report_date)} at {fmtTime(selectedReport.created_at)}
                </span>
              </div>
              <button onClick={() => setSelectedReport(null)}
                style={{ fontSize: 11, color: 'var(--gray)', background: 'none', border: '1px solid var(--border)', borderRadius: 5, padding: '4px 10px', cursor: 'pointer' }}>
                Close
              </button>
            </div>
            <div
              style={{ padding: 20 }}
              dangerouslySetInnerHTML={{ __html: selectedReport.report_html }}
            />
          </div>
        )}

        {/* Activity log (from summary data) */}
        {selectedReport?.summary?.activity_log_today?.length > 0 && (
          <div style={{ background: 'var(--card-bg)', border: '1px solid var(--border)', borderRadius: 12, padding: '16px 20px' }}>
            <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 10 }}>📋 Activity Log</div>
            <div style={{ maxHeight: 300, overflowY: 'auto' }}>
              {selectedReport.summary.activity_log_today.map((a, i) => (
                <div key={i} style={{ display: 'grid', gridTemplateColumns: '80px 140px 1fr 140px', padding: '6px 0', borderBottom: '1px solid var(--border)', fontSize: 12, alignItems: 'center' }}>
                  <span style={{ color: 'var(--gray)' }}>{fmtTime(a.time)}</span>
                  <span style={{ fontWeight: 600 }}>{a.coordinator}</span>
                  <span>{a.detail || a.action}</span>
                  <span style={{ color: 'var(--gray)' }}>{a.patient}</span>
                </div>
              ))}
            </div>
          </div>
        )}

      </div>
    </div>
  );
}
